---
title: "5-Intro_Stats"
author: "CM Gienger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(emmeans)
```

Note error between GardenOzone.csv and ozone.csv input files
Known issue

```{r}
#import data
lady <- read.csv("ladybirds_morph_colour.csv")
```

```{r}
# Check it out
glimpse(lady)
```

```{r}
#organize data for plotting/analysis

totals <- lady %>%
  group_by(Habitat, morph_colour) %>%
  summarise(total.number = sum(number))

totals
```

```{r}
ggplot(totals, aes(x = Habitat, y = total.number,
                   fill = morph_colour)) +
  geom_bar(stat = 'identity', position = 'dodge')
```

```{r}
#Change the bar colors
ggplot(totals, aes(x = Habitat, y = total.number,
                   fill = morph_colour)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c(black = "black", red = "red"))
```

```{r}
#Making the χ2 Test
totals
```
```{r}
lady.mat <- xtabs(number ~ Habitat + morph_colour,
                  data = lady)
lady.mat
```

```{r}
chisq.test(lady.mat)
```


```{r}
#Two-sample t-test
ozone <- read.csv("ozone.csv")
glimpse(ozone)
```

```{r}
ggplot(ozone, aes(x = Ozone)) +
  geom_histogram(binwidth = 10) +
  facet_wrap(~ Garden.location, ncol = 1) +
  theme_bw()
```
```{r}
ggplot(ozone, aes(x = Garden.location, y = Ozone, color = Garden.location)) +
  geom_point(size=3) +
  theme_bw()
```


```{r}
# Do a t.test now....
t.test(Ozone ~ Garden.location, data = ozone)
```

